Yoast/clicky

- readme.txt
The `Text domain` tag should be used in the plugin header in the main PHP file, not in the readme.
Refs:
* https://developer.wordpress.org/plugins/plugin-basics/header-requirements/
* https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/
Fixes #8
> QA: remove text-domain from readme.txt

- admin/views/meta-box.php
Now, there are a couple of things fixed in one go here.
To start, the phrase contains placeholders and therefore needs a translators comment.
To add the translators comment, the embedded PHP would become multi-line (well, it already was, but shouldn't have been).
When embedded PHP is multi-line, the PHP open and close tags should each be on their own line without any other content.
And as the snippet now has become a multi-line snippet anyway, we may as well make the function call more readable by making it a proper multi-line function call.
Lastly, the phrase contained a new line character. These are meaningless in .po files and confusing for translators - should this be a `<br>` ?, does the format matter ? -, so this new line character has been removed.
> CS: fix formatting of embedded PHP

- tests/bootstrap.php
Do more rigorous checking whether the environment is correctly set up for the unit tests to be run and if not, show an instructive error message.
See PR https://github.com/Yoast/wpseo-woocommerce/pull/371
> QA: review test bootstrap file / show friendly errors

- tests/framework/index.php
- tests/index.php
As the tests are not shipped with the plugin, the test directories do not need an `index.php` file to prevent incorrectly configured servers from serving a file list.
> CS/QA: remove redundant index.php files

- admin/class-clicky-admin-page.php
- admin/class-clicky-admin.php
- admin/class-clicky-options-admin.php
- frontend/class-clicky-frontend.php
- tests/test-class-clicky-admin.php
- tests/test-class-clicky-options-admin.php
`include` and `require` are language constructs, not functions.
With that in mind there are a number of best practices surrounding them:
* There is no need to use parenthesis and not doing so will be, albeit marginally, faster.
* Always pass an absolute path for maximum portability. The `clicky.php` file defines the `CLICKY_PLUGIN_DIR_PATH` constant to be used for that (includes trailing slash), WP itself has `ABSPATH` (includes trailing slash).
~~The Clicky unit tests did not have a good constant available for this so far, this has been fixed by adding a `CLICKY_TESTS_PATH` constant (including trailing slash) to the `bootstrap.php` file.~~ _(removed, superseded by another commit making this unnecessary)_
* As all the relevant PATH constants already contain a trailing slash, there is no …
> CS/QA: review of all include and require statements

- frontend/class-clicky-frontend.php
- frontend/class-clicky-visitor-graph.php
- tests/test-class-clicky-options.php
Strict type comparisons should be used as a rule, with loose type comparisons being the exception.
This is especially important when comparing variables which are expected to be strings, as when one of the two operands - for whatever reason, other plugins interfering, errors etc - is not a string, the other operand will be juggled to the type of the first operand which can lead to unexpected results and hard to debug bugs.
Ref: http://phpcheatsheets.com/compare/equal/
> CS: Use strict comparisons

- admin/class-clicky-options-admin.php
WPCS 1.1.0 introduced a stricter check on function call layouts.
Multi-line function calls now need to have each argument on a new line.
In a next iteration of this principle, it is expected that a sniff will be introduced to ban multi-line function call arguments.
With this mind, function calls with multi-line parameters which are currently already causing errors to be thrown by PHPCS after the changes in WPCS 1.1.0, have been fixed - depending on the existing code - by:
* either changing multi-line function call arguments to single line;
* or by moving a multi-line function call arguments out of the function call and defining it as a variable before passing it to the function call.
This commit contains changes for the second variant.
> CS: Move multi-line parameters out of function calls

- tests/test-class-clicky-options-admin.php
The default visibility is `public`, so for those methods and properties where the visibility was missing, I've elected to set them all to `public` so as not to break backward-compatibility.
> CS: all methods and properties should have visibility declared

- frontend/class-clicky-visitor-graph.php
Using a simple `include` will have the same effect.
> QA: don't use readfile unnecessarily

- admin/class-clicky-admin.php
- admin/views/stats-page.php
- tests/test-class-clicky-admin.php
A little more involved change.
* Use the WP native `add_query_arg()` function rather than the PHP native `http_build_query()`.
* Escape the URL in the HTML output.
* Adjust the unit test to reflect the updated code.
> CS/XSS: always escape output [4]

- admin/class-clicky-admin-page.php
- admin/class-clicky-admin.php
- admin/class-clicky-options-admin.php
Simple ones. Use `esc_html()`, `esc_attr()` or `esc_url()` where appropriate.
Includes changing the function calls from single line to multi-line for improved readability.
> CS/XSS: always escape output [2]

- tests/test-class-clicky-admin.php
WPCS 1.1.0 introduced a stricter check on function call layouts.
Multi-line function calls now need to have each argument on a new line.
In a next iteration of this principle, it is expected that a sniff will be introduced to ban multi-line function call arguments.
With this mind, function calls with multi-line parameters which are currently already causing errors to be thrown by PHPCS after the changes in WPCS 1.1.0, have been fixed - depending on the existing code - by:
* either changing multi-line function call arguments to single line;
* or by moving a multi-line function call arguments out of the function call and defining it as a variable before passing it to the function call.
This commit contains changes for the first variant.
> CS: Use a single line for function call-back arrays as function call parameters

- admin/class-clicky-admin.php
- admin/class-clicky-options-admin.php
WPCS 1.1.0 introduced a stricter check on function call layouts.
Multi-line function calls now need to have each argument on a new line.
See:
* https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/releases/tag/1.1.0
* https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/1330
This commit addresses multi-line function calls where parameters did not each start on a new line.
Also note that non-associative arrays don't have to be multi-line and - especially for call-backs - using single-line format can improve the readability of the code.
> CS: Each parameter should start on a new line in multi-line function calls

- tests/framework/class-clicky-unit-test-case.php
- tests/test-class-clicky-admin-page.php
- tests/test-class-clicky-admin.php
- tests/test-class-clicky-options-admin.php
- tests/test-class-clicky-options.php
This is a long established best practice.
PHPUnit contains a variety of assertions and the ones available has been extended hugely over the years.
To have the most reliable tests, the most specific assertion should be used.
This implements this for the Clicky plugin, while keeping in mind that at this time, PHPUnit 4.x should still be supported.
Refs:
* https://phpunit.de/manual/4.8/en/appendixes.assertions.html
* https://phpunit.readthedocs.io/en/7.5/assertions.html#
Most notably, this changes calls to `assertEquals()` to `assertSame()`, where `assertEquals()` does a loose type comparison and `assertSame()` does a strict type comparison.
Refs:
* https://phpunit.de/manual/6.5/en/appendixes.assertions.html#appendixes.assertions.assertEquals
* …
> QA: use the most specific PHPUnit assertion possible

- .travis.yml
The minimum supported WP version was updated to WP 5.1 in 3bdeb47afc7c5571c7a7d94f6623ff70e7f28e1b, but WP 5.0 was still being used in the Travis script.
> Travis: bring versions in line with minimum supported version

- admin/class-clicky-admin-page.php
- admin/class-clicky-admin.php
Sometimes it is easier to escape data at the point of building an HTML string, than to use late escaping.
This is a functional change. The change has not been tested (yet).
While I expect no problems, testing the change is recommended.
> CS/XSS: always escape output [6]

- admin/class-clicky-admin-page.php
- admin/views/admin-page.php
- admin/views/meta-box.php
When a variable is used as part of an attribute or url, it is always better to escape the whole string as that way a potential escape character just before the variable will be correctly escaped.
Without the context of the complete string, - even when the variable is escaped - it may still leave you open to security issues.
> CS/XSS: always escape output [3]

- frontend/views/comment-author-script.php
- frontend/views/script.php
The correct way to escape variable data within a javascript snippet is to use `wp_json_encode()`.
Also see: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/1270
This is a functional change. The change has not been tested (yet).
While I expect no problems, testing the change is recommended.
> CS/XSS: always escape output [5]

- admin/class-clicky-admin.php
`floatval` is mostly intended to be used with call-backs.
For an ordinary cast-to-float, using a type cast is more performant than using the function call.
This is a code-only change and should be safe to merge without testing.
> CS: use cast rather than function call

- tests/test-class-clicky-options-admin.php
`assertContains()` can be used to examine both arrays as well as strings.
When passed a string as the `$haystack`, it will examine it to see if the `$needle` exists in the string.
So, basically that function does the same as the current test was doing, but then using PHPUnit native assertions,
Ref:
* https://phpunit.de/manual/6.5/en/appendixes.assertions.html#appendixes.assertions.assertContains#appendixes.assertions.assertContains.example2
> QA: Unit tests: use a more appropriate assertion

- tests/framework/class-clicky-unit-test-case.php
- tests/test-class-clicky-admin-page.php
- tests/test-class-clicky-admin.php
- tests/test-class-clicky-options-admin.php
- tests/test-class-clicky-options.php
For PHPUnit assertions which expect an `$expected` and a `$result` parameter, the parameter order is always `( $expected, $result, ...).
While it may not seem important to use the correct parameter order for assertions doing a straight comparison, in actual fact, it is.
The PHPUnit output when the assertions fail expects this order and the failure message will be reversed if the parameters are passed in reversed order which leads to confusion and makes it more difficult to debug a failing test.
Refs:
* https://phpunit.de/manual/6.5/en/appendixes.assertions.html#appendixes.assertions.assertSame
> QA: Unit tests: use the correct parameter order

- admin/class-clicky-admin-page.php
Loading scripts in the page footer instead of in the page header means that they will not block the rendering of the page while loading.
This is a functional change. The change has not been tested (yet).
While I expect no problems, testing the change is recommended.
> CS/QA: load scripts in a non-blocking way

- admin/admin-page.php
The `$content` should be properly escaped.
> QA/Output escaping: remove whitelisting

- .travis.yml
- tests/bin/code_climate.sh
Travis does not fail the build when there are multiple commands within a condition.
This means that, in this case, if the unit tests on the PHP 7.3 build would fail, Travis would still show a passing build.
Removing the `code_climate.sh` script and moving the Codeclimate reporting to the `after_script` section of the Travis script fixes this.
> Travis: fix test failures not being reported

- frontend/class-clicky-visitor-graph.php
https://github.com/Yoast/clicky/issues/65 - double slash causing PHP warnings
> Remove additional slash

- composer.lock
The update of the `composer.lock` file done in 42d1179 was run on PHP 7.2 or higher. This is causing issues as PHP 5.6 still needs to be supported by the Clicky plugin.
This PR contains two commits.
The first reverting the changes to the `composer.lock` file after 003505ad99119b619075dec1e5b08988c7b27bbf.
The second selectively re-doing the dependency updates, but with composer running on PHP 5.6 which prevents dependencies being updated to versions which are incompatible PHP-cross-version.
* On `develop` try running a `composer install` while on PHP 5,6 and see it fail.
* Now switch to this branch, run `composer install` while on PHP 5.6 and see the install succeed.
> Fix invalid `composer.lock` file

- .travis.yml
- composer.json
- composer.lock
- readme.txt
Includes:
* Add missing `Requires PHP` and `License` headers to the `readme.txt` file.
* Add missing `php` requirement to the `composer.json` file.
* Removing builds against PHP < 5.6.
* Removing the build against PHP 7.4 from allowed failures.
* Adding back a build against PHP `nightly` (PHP 8).
* Adjusting the Travis matrix for dropped support of WP < 5.2.
* Using the composer scripts to run various tasks.
* Dropping PHPUnit < 5.7 from the Composer `require-dev`.
Also:
* Travis hasn't supported `sudo` for quite a while now, so removing it.
* Add a `composer test` script to be in line with the other plugins.
~~This PR depends on PR #73 and can be changed from `draft` to `ready for review` once PR #73 has been merged.~~
Closes #72
Closes https://github.com/Yoast/wordpress-seo/issues/13758
> Stop explicit support for PHP < 5.6 / WP < 5.2

- .phpcs.xml.dist
- admin/admin-page.php
- admin/admin.php
- admin/options-admin.php
- admin/views/admin-page.php
- clicky.php
- composer.json
- composer.lock
- frontend/frontend.php
- frontend/visitor-graph.php
- includes/options.php
- tests/admin-page-test.php
- tests/admin-test.php
- tests/bootstrap.php
- tests/options-admin-test.php
This updates the dependency in `composer.json`, as well as the PHPCS ruleset for YoastCS 2.0.0.
Includes:
* A selective update of the `composer.lock` for just YoastCS and its dependencies.
* Removing the tweaks to the Composer `check-cs` script to allow for warnings (no longer needed).
Ref: https://github.com/Yoast/yoastcs/releases/tag/2.0.0
This deprecates the `clicky_admin_footer` action hook in favour of the `Yoast\WP\Clicky\admin_footer` hook.
[This needs a changelog entry]
See the test instructions in the Yoast/wpseo-woocommerce#451 PR for guidance on how to test this PR.
> PHPCS: Update to YoastCS 2.0.0

- tests/bootstrap.php
Minor code simplification which is possible now PHP 5.6 is the minimum version.
> Modernize: use `__DIR__` instead of `dirname( __FILE__ )`

- admin/admin-page.php
1. PHP has no concept of named passed parameters, so `$protocol[l]s` is useless here.
2. `null` and `display` are the defaults for respective parameters of the `esc_url()` function, so don't need to be passed.
Ref: https://developer.wordpress.org/reference/functions/esc_url/
> QA: remove unnecessary function call parameters

- .travis.yml
- composer.json
- composer.lock
- tests/bin/phplint.sh
This installs two additional PHP packages in `require-dev`:
* [`php-parallel-lint`](https://packagist.org/packages/jakub-onderka/php-parallel-lint) which allows for linting PHP files in parallel (faster), as well as automatically recursively walking directories.
* [`php-console-highlighter`](https://packagist.org/packages/jakub-onderka/php-console-highlighter) which provides PHP code highlighting in the command line console, allowing the linter to display the results in a more meaningful manner.
It also adds a new `lint` script for use with Composer.
* Switch out the script part in the Travis script which did the linting the "old-fashioned" way to use the new Parallel linting option.
Includes removing the `tests/bin/phplint.sh` file.
* Adjust the `composer install` command in the …
> Travis/Composer: switch over to parallel linting of PHP files

- admin/admin-page.php
This fixes the Clicky blog feed to be retrieved properly.
> Change the Clicky blog feed URL

- .travis.yml
- composer.json
As the tests for the Clicky plugin don't use mocking, the tests will run fine with PHPUnit 7.x on PHP 8.
All that is needed is to `ignore-platform-reqs` and as this repo has a committed `composer.lock` file, we also force installation of PHPUnit 7.x.
Includes adding `travis_retry` to `composer install`-like commands to get round builds stalling on the connection with Packagist.
Includes fixing the `composer test` command for cross-platform (i.e. Windows) compatibility.
> Travis: run the tests against PHP 8/nightly
